/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class realHTML_jni_JNI */

#ifndef _Included_realHTML_jni_JNI
#define _Included_realHTML_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     realHTML_jni_JNI
 * Method:    jni_createUDS_Server
 * Signature: (Ljava/lang/String;Ljava/lang/Boolean;)I
 */
JNIEXPORT jint JNICALL Java_realHTML_jni_JNI_jni_1createUDS_1Server
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     realHTML_jni_JNI
 * Method:    jni_waitForClient
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_realHTML_jni_JNI_jni_1waitForClient
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     realHTML_jni_JNI
 * Method:    jni_startNaturalWS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_realHTML_jni_JNI_jni_1startNaturalWS
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     realHTML_jni_JNI
 * Method:    jni_getChildProcessStatus
 * Signature: (I)LrealHTML/jni/ChildProcess;
 */
JNIEXPORT jobject JNICALL Java_realHTML_jni_JNI_jni_1getChildProcessStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     realHTML_jni_JNI
 * Method:    jni_killChildProcess
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_realHTML_jni_JNI_jni_1killChildProcess
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     realHTML_jni_JNI
 * Method:    jni_sendMessageToNatural
 * Signature: (ILrealHTML/jni/natural/Message;)V
 */
JNIEXPORT void JNICALL Java_realHTML_jni_JNI_jni_1sendMessageToNatural
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
